// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsF0YdI19K4mjzCOsUUw-y0yMN6S0_zY',
    appId: '1:987947532334:web:6d3ca417fa4d71015a5fbf',
    messagingSenderId: '987947532334',
    projectId: 'note-list-app',
    authDomain: 'note-list-app.firebaseapp.com',
    storageBucket: 'note-list-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJaVn-o_h5A5nhElcZUb3_GYLz4DpOAgE',
    appId: '1:987947532334:android:b15028b6e30f057a5a5fbf',
    messagingSenderId: '987947532334',
    projectId: 'note-list-app',
    storageBucket: 'note-list-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEDfZooX6BiO43B3-17CsjXqzQ-cUK_qQ',
    appId: '1:987947532334:ios:59fde9c42a041a245a5fbf',
    messagingSenderId: '987947532334',
    projectId: 'note-list-app',
    storageBucket: 'note-list-app.appspot.com',
    iosClientId: '987947532334-m9nreb36g0d74scunqtloj01c2c01usf.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEDfZooX6BiO43B3-17CsjXqzQ-cUK_qQ',
    appId: '1:987947532334:ios:59fde9c42a041a245a5fbf',
    messagingSenderId: '987947532334',
    projectId: 'note-list-app',
    storageBucket: 'note-list-app.appspot.com',
    iosClientId: '987947532334-m9nreb36g0d74scunqtloj01c2c01usf.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
